name: Turnstyle
run-name: Test 3 - Sleep ${{ format('{0}', inputs.delay) }}
on:
  workflow_dispatch:
    inputs:
      delay:
        type: number
        required: true
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job start $(date)"
      - name: Turnstyle
        uses: meisterplan/action-turnstyle@31730aa7d2d985df3bfa6d37808bf25aed6d69e8
        with:
          abort-after-seconds: 600
          poll-interval-seconds: 10 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Job serial execution start $(date)"
      - run: "sleep ${{ format('{0}', inputs.delay) }}"
      - run: echo "Job serial execution finish $(date)"
