name: Turnstyle
run-name: Test 2 - Sleep ${{ format('{0}', inputs.delay) }}
on:
  workflow_dispatch:
    inputs:
      delay:
        type: number
        required: true
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job start $(date)"
      - name: Turnstyle
        uses: softprops/turnstyle@ca99add00ff0c9cbc697d22631d2992f377e5bd5
        with:
          abort-after-seconds: 600
          poll-interval-seconds: 10
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Job serial execution start $(date)"
      - run: "sleep ${{ format('{0}', inputs.delay) }}"
      - run: echo "Job serial execution finish $(date)"
